from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


def _ts_string(value: str) -> str:
    return json.dumps(value)


def _constraint_from_version(version: str | None) -> str | None:
    if not version:
        return None
    match = re.match(r"^(\d+\.\d+)(?:\.(\d+))?", version)
    if not match:
        return None
    major_minor = match.group(1)
    patch = match.group(2) or "0"
    return f">={major_minor}.{patch}"


def _load_generated_rows(path: str | None) -> dict[str, dict[str, Any]]:
    if not path:
        return {}
    rows = json.loads(Path(path).read_text(encoding="utf-8"))
    by_key = {row.get("key"): row for row in rows if row.get("key")}
    return by_key


def complete_feature_input(feature_input: dict[str, Any], generated_features_path: str | None = None) -> dict[str, Any]:
    """Fill omitted constraints/sources from generated canitf feature rows by key.

    Human input stays authoritative; changelog/cani.tf generated rows only fill
    missing fields to make the workflow semi-automated rather than fully inferred.
    """
    generated = _load_generated_rows(generated_features_path)
    output = json.loads(json.dumps(feature_input))
    for feature in output.get("features", []):
        row = generated.get(feature.get("key"))
        if not row:
            continue
        constraints = feature.setdefault("constraints", {})
        for tool, data in row.get("tools", {}).items():
            constraints.setdefault(tool, _constraint_from_version(data.get("version")))
        existing_sources = set(feature.setdefault("sources", []))
        for src in row.get("sources", []):
            if src not in existing_sources:
                feature["sources"].append(src)
                existing_sources.add(src)
    return output


def render_cdktn_source(feature_input: dict[str, Any], baseline: str | None = None) -> str:
    baseline = baseline or feature_input.get("baseline", "1.7.5")
    features = feature_input.get("features", [])
    lines = [
        "// Copyright (c) HashiCorp, Inc",
        "// SPDX-License-Identifier: MPL-2.0",
        "//",
        "// Generated by canitf-project. Edit data/hcl-feature-input.json, then run:",
        "//   canitf generate-cdktn-source --features-input data/hcl-feature-input.json --generated-features data/features.json --out data/cdktn-feature-constraints.ts",
        "//",
        f"// Baseline: Terraform/OpenTofu feature comparison starts at Terraform {baseline} for cdk-terrain validation work.",
        "// Note: OpenTofu did not fork from Terraform 1.7.5; 1.7.5 is the cdk-terrain baseline.",
        "",
        "import { TerraformFeatureVersionConstraints, ValidateTerraformFeatureVersion } from \"./validate-terraform-feature-version\";",
        "",
        "export interface TerraformFeatureConstraintSpec {",
        "  readonly featureName: string;",
        "  readonly constraints: TerraformFeatureVersionConstraints;",
        "  readonly category?: string;",
        "  readonly cdktnUseCase?: string;",
        "  readonly sources?: readonly string[];",
        "}",
        "",
        "export const TERRAFORM_HCL_FEATURE_CONSTRAINTS = {",
    ]
    for feature in features:
        key = feature["key"]
        lines.append(f"  {_ts_string(key)}: {{")
        lines.append(f"    featureName: {_ts_string(feature['name'])},")
        constraints = feature.get("constraints", {})
        lines.append("    constraints: {")
        for tool in ("terraform", "opentofu"):
            if constraints.get(tool):
                lines.append(f"      {tool}: {_ts_string(constraints[tool])},")
        lines.append("    },")
        if feature.get("category"):
            lines.append(f"    category: {_ts_string(feature['category'])},")
        if feature.get("cdktnUseCase"):
            lines.append(f"    cdktnUseCase: {_ts_string(feature['cdktnUseCase'])},")
        if feature.get("sources"):
            lines.append("    sources: [")
            for src in feature["sources"]:
                lines.append(f"      {_ts_string(src)},")
            lines.append("    ],")
        lines.append("  },")
    lines += [
        "} as const satisfies Record<string, TerraformFeatureConstraintSpec>;",
        "",
        "export type TerraformHclFeatureKey = keyof typeof TERRAFORM_HCL_FEATURE_CONSTRAINTS;",
        "",
        "export function validateTerraformHclFeatureVersion(",
        "  featureKey: TerraformHclFeatureKey,",
        "  hint?: string,",
        "): ValidateTerraformFeatureVersion {",
        "  const spec = TERRAFORM_HCL_FEATURE_CONSTRAINTS[featureKey];",
        "  return new ValidateTerraformFeatureVersion(",
        "    spec.featureName,",
        "    spec.constraints,",
        "    undefined,",
        "    undefined,",
        "    hint,",
        "  );",
        "}",
        "",
    ]
    return "\n".join(lines)


def generate_cdktn_source(features_input_path: str, out_path: str, generated_features_path: str | None = None, baseline: str | None = None) -> None:
    feature_input = json.loads(Path(features_input_path).read_text(encoding="utf-8"))
    completed = complete_feature_input(feature_input, generated_features_path)
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_cdktn_source(completed, baseline=baseline), encoding="utf-8")
