// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0
//
// Generated by canitf-project. Edit data/hcl-feature-input.json, then run:
//   canitf generate-cdktn-source --features-input data/hcl-feature-input.json --generated-features data/features.json --out data/cdktn-feature-constraints.ts
//
// Baseline: Terraform/OpenTofu feature comparison starts at Terraform 1.7.5 for cdk-terrain validation work.
// Note: OpenTofu did not fork from Terraform 1.7.5; 1.7.5 is the cdk-terrain baseline.

import { TerraformFeatureVersionConstraints, ValidateTerraformFeatureVersion } from "./validate-terraform-feature-version";

export interface TerraformFeatureConstraintSpec {
  readonly featureName: string;
  readonly constraints: TerraformFeatureVersionConstraints;
  readonly category?: string;
  readonly cdktnUseCase?: string;
  readonly sources?: readonly string[];
}

export const TERRAFORM_HCL_FEATURE_CONSTRAINTS = {
  "s3-native-state-locking": {
    featureName: "S3 native state locking",
    constraints: {
      terraform: ">=1.10.0",
      opentofu: ">=1.10.0",
    },
    category: "backend",
    cdktnUseCase: "S3BackendConfig.useLockfile",
    sources: [
      "https://developer.hashicorp.com/terraform/language/v1.10.x/upgrade-guides#s3-backend",
      "https://opentofu.org/docs/intro/whats-new/#native-s3-state-locking",
    ],
  },
  "provider-defined-functions": {
    featureName: "Provider-defined functions",
    constraints: {
      terraform: ">=1.8.0",
      opentofu: ">=1.7.0",
    },
    category: "hcl-functions",
  },
  "configured-provider-defined-functions": {
    featureName: "Configured provider-defined functions",
    constraints: {
      opentofu: ">=1.7.0",
    },
    category: "hcl-functions",
  },
  "override-resource-data-module": {
    featureName: "Test override blocks",
    constraints: {
      terraform: ">=1.7.0",
      opentofu: ">=1.8.0",
    },
    category: "tests",
  },
  "ephemeral-values-and-resources": {
    featureName: "Ephemeral values and resources",
    constraints: {
      terraform: ">=1.10.0",
      opentofu: ">=1.11.0",
    },
    category: "hcl-ephemerality",
    sources: [
      "https://developer.hashicorp.com/terraform/language/resources/ephemeral",
      "https://opentofu.org/docs/language/ephemerality/ephemeral-resources/",
    ],
  },
  "write-only-attributes": {
    featureName: "Write-only attributes",
    constraints: {
      terraform: ">=1.11.0",
      opentofu: ">=1.11.0",
    },
    category: "hcl-ephemerality",
    sources: [
      "https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only",
      "https://opentofu.org/docs/main/language/ephemerality/write-only-attributes/",
    ],
  },
  "backend-configuration-using-locals-and-variables": {
    featureName: "Backend configuration using locals and variables",
    constraints: {
      opentofu: ">=1.8.0",
    },
    category: "backend",
    sources: [
      "https://github.com/hashicorp/terraform/issues/13022",
    ],
  },
} as const satisfies Record<string, TerraformFeatureConstraintSpec>;

export type TerraformHclFeatureKey = keyof typeof TERRAFORM_HCL_FEATURE_CONSTRAINTS;

export function validateTerraformHclFeatureVersion(
  featureKey: TerraformHclFeatureKey,
  hint?: string,
): ValidateTerraformFeatureVersion {
  const spec = TERRAFORM_HCL_FEATURE_CONSTRAINTS[featureKey];
  return new ValidateTerraformFeatureVersion(
    spec.featureName,
    spec.constraints,
    undefined,
    undefined,
    hint,
  );
}
